on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage_code-cov
codecov:
  token: ${{ secrets.CODECOV_TOKEN }}
comment: false
coverage:
  status:
    patch:
      default:
        informational: true
        target: auto
        threshold: 1.0
    project:
      default:
        informational: true
        target: auto
        threshold: 1.0
